SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.Goals', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[Goals](
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[UserId] INT FOREIGN KEY REFERENCES [dbo].[Users]([Id]) NOT NULL,
	[Title] NVARCHAR(128) NOT NULL,
	[Description] NVARCHAR(2048) NOT NULL,
	[CreatedDate] DATETIME2 DEFAULT CURRENT_TIMESTAMP NOT NULL,
	[Status] INT FOREIGN KEY REFERENCES [dbo].[GoalStatuses]([Id]),
	[IsPublic] BIT DEFAULT 0 NOT NULL
	) WITH (DATA_COMPRESSION = ROW);
END;

IF INDEXPROPERTY(OBJECT_ID(N'dbo.Goals'), 'IX_Goals_UserId', 'IndexId') IS NULL
BEGIN
	CREATE NONCLUSTERED INDEX [IX_Goals_UserId] ON [dbo].[Goals]([UserId]);
END;

GO
