SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.GoalStatuses', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[GoalStatuses](
	[Id] INT PRIMARY KEY,
	[Status] NVARCHAR(64) NOT NULL,
	[Description] NVARCHAR(128) NOT NULL
	) WITH (DATA_COMPRESSION = ROW);
END;

GO
