SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.Users', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[Users](
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[EmailAddress] NVARCHAR(128) UNIQUE NOT NULL,
	[FirstName] NVARCHAR(128) NOT NULL,
	[LastName] NVARCHAR(128) NOT NULL,
	[PasswordHash] VARBINARY(64) NOT NULL, --to fit SHA-512
	[PasswordSalt] VARBINARY(128),
	[CreatedDate] DATETIME2 DEFAULT CURRENT_TIMESTAMP,
	[IsDeleted] BIT NOT NULL DEFAULT 0
	) WITH (DATA_COMPRESSION = ROW);
END;

IF INDEXPROPERTY(OBJECT_ID(N'dbo.Users'), 'IX_Users_EmailAddress', 'IndexId') IS NULL
BEGIN
	CREATE NONCLUSTERED INDEX [IX_Users_EmailAddress] ON [dbo].[Users]([EmailAddress]);
END;

GO
